services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    hostname: scylla-node1
    platform: ${DOCKER_PLATFORM}
    command: --reactor-backend="${SCYLLA_BACKEND}" --smp 1 --developer-mode 1 #--overprovisioned 1
    ports:
      - 9042:9042 # Use this port for the Cassandra native protocol ( cli uses )
      # - 9100:9100 # Node Exporter
      # - 9180:9180 # Scylla Metrics
      # - 9160:9160 # Use this port for the thrift protocol
      # - 7199:7199 # Use this port for JMX
    volumes:
      - scylla_data1:/var/lib/scylla
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --no-color --debug --request-timeout=5 -e 'SELECT cluster_name FROM system.local' scylla-node1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  scylla-node2:
    image: scylladb/scylla:latest
    container_name: scylla-node2
    hostname: scylla-node2
    platform: ${DOCKER_PLATFORM}
    command: --seeds=scylla-node1 --reactor-backend="${SCYLLA_BACKEND}" --smp 1 --developer-mode 1 #--overprovisioned 1
    ports:
      - 9043:9042 # Use this port for the Cassandra native protocol ( cli uses )    
    volumes:
      - scylla_data2:/var/lib/scylla
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --no-color --debug --request-timeout=5 -e 'SELECT cluster_name FROM system.local' scylla-node2"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s      
    depends_on:
      - scylla-node1

  scylla-node3:
    image: scylladb/scylla:latest
    container_name: scylla-node3
    hostname: scylla-node3
    platform: ${DOCKER_PLATFORM}
    command: --seeds=scylla-node1 --reactor-backend="${SCYLLA_BACKEND}" --smp 1 --developer-mode 1 #--overprovisioned 1
    ports:
      - 9044:9042 # Use this port for the Cassandra native protocol ( cli uses )    
    volumes:
      - scylla_data3:/var/lib/scylla
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --no-color --debug --request-timeout=5 -e 'SELECT cluster_name FROM system.local' scylla-node3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s      
    depends_on:
      - scylla-node1

volumes:
  scylla_data1:
  scylla_data2:
  scylla_data3:

networks:
  scylla-net:
    driver: bridge