version: '3.8'
services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    hostname: scylla-node1
    command: --platform linux/arm64/v8 --seeds=scylla-node1 --smp 1 --developer-mode 1
    ports:
      - 9100:9100 # Node Exporter
      - 9180:9180 # Scylla Metrics
      - 9042:9042 # Use this port for the Cassandra native protocol
      - 9160:9160 # Use this port for the thrift protocol
      - 7199:7199 # Use this port for JMX
    volumes:
      - scylla_data1:/var/lib/scylla
    networks:
      - scylla-net

  scylla-node2:
    image: scylladb/scylla:latest
    container_name: scylla-node2
    hostname: scylla-node2
    command: --platform linux/arm64/v8 --seeds=scylla-node1 --smp 1 --developer-mode 1
    volumes:
      - scylla_data2:/var/lib/scylla
    networks:
      - scylla-net
    depends_on:
      - scylla-node1

  scylla-node3:
    image: scylladb/scylla:latest
    container_name: scylla-node3
    hostname: scylla-node3
    command: --platform linux/arm64/v8 --seeds=scylla-node1 --smp 1 --developer-mode 1
    volumes:
      - scylla_data3:/var/lib/scylla
    networks:
      - scylla-net
    depends_on:
      - scylla-node1

volumes:
  scylla_data1:
  scylla_data2:
  scylla_data3:

networks:
  scylla-net:
    driver: bridge